language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libatlas-base-dev
      - gfortran
      - python-scipy
install:
  - pip install --upgrade pip
  - pip install networkx
  - pip install matplotlib
  - pip install scipy
before_script:
  - export PYTHONPATH='.'
script: python tests/AmazonTest.py
